### ISSUE TITLE
http://localhost:3000 not working

### ISSUE THREAD

**Issue by cuongtran3001** [grouparoo/grouparoo#192] opened 2020-06-01 09:17 UTC
Hi Grouparoo team,
I have followed the instruction to run app and go to step 4:
**Run npm start to start the server and visit http://localhost:3000 to get started. Follow the on-screen instructions to create your account and first team.**

Here is the result:

> @grouparoo/app-local-public@0.1.2 start /mnt/d/Project/grouparoo/apps/local-public
> cd node_modules/@grouparoo/core && GROUPAROO_MONOREPO_APP=local-public ./api/bin/start

2020-06-01T09:12:27.613Z - info: registering grouparoo plugin: @grouparoo/core/manual
2020-06-01T09:12:27.615Z - info: registering grouparoo plugin: @grouparoo/core/events
2020-06-01T09:12:27.617Z - notice: pid: 424
2020-06-01T09:12:27.618Z - notice: environment: development
2020-06-01T09:12:27.619Z - info: *** Starting Actionhero ***
2020-06-01T09:12:27.622Z - info: using path "/mnt/d/Project/grouparoo/apps/local-public/node_modules/@grouparoo/core/api/files/development" for Grouparoo file storage
2020-06-01T09:12:27.633Z - info: actionhero member 192.168.1.53 has joined the cluster
2020-06-01T09:12:27.689Z - notice: server ID: 192.168.1.53
2020-06-01T09:12:27.690Z - notice: *** Actionhero Started ***

When opening the brower to access http://localhost:3000 but nothing happend and get the message: This site can’t be reached

Any step that i am missing please help to correct?

Tks,
Cuong Tran

**Comment by evantahler** [comment] 2020-06-01 15:25
Hi @cuongtran3001! It looks like you might not have set the required environment variables noted in step 2 [here](https://github.com/grouparoo/grouparoo/blob/master/documents/deployment/getting-started.md).  With `WEB_SERVER=true` and `PORT={some port}` there will be additional log messages about the web server starting.

**Comment by cuongtran3001** [comment] 2020-06-02 01:09
Hi @evantahler,
My .env looks like this:

#############
## GENERAL ##
#############

# For the API server; the web server runs on port 3000 locally
PORT=3000
WEB_URL=http://localhost:3000

WEB_SERVER=true
SCHEDULER=true
WORKERS=1

###########
## REDIS ##
###########

REDIS_URL="redis://localhost:6379"

##############
## DATABASE ##
##############

DATABASE_URL="postgresql://localhost:5432/grouparoo_development"
SERVER_TOKEN=a_random_token

Here are screenshots:
<img width="618" alt="1" src="https://user-images.githubusercontent.com/4277357/83468903-596d0780-a4a8-11ea-95f8-44b75e95f4b0.PNG">
<img width="832" alt="2" src="https://user-images.githubusercontent.com/4277357/83468907-5a9e3480-a4a8-11ea-8501-3092defa8264.PNG">
<img width="597" alt="3" src="https://user-images.githubusercontent.com/4277357/83468908-5b36cb00-a4a8-11ea-8841-35aabf41e4e9.PNG">

Thanks,
Cuong Tran

**Comment by evantahler** [comment] 2020-06-02 04:38
Hmm... can you share the path location of your `.env` file in relation to your package.json file?  listing `ls -la` in that directory will be helpful.  Can you also try inlining all the ENV options with the start command, just to ensure that the problem is isolated to loading the ENV vs something else?  ie: 
```
PORT=3000 WEB_URL="http://localhost:3000" WEB_SERVER=true SCHEDULER=true WORKERS=1 ... npm start
```

 Also, it looks like you are editing the `.env` file in a windows environment, but perhaps running the app in a docker or WSL environment?  As a note, Grouparoo only works on Luinux and OSX at the moment... we'd love help getting it to work on Windows (if that's what you are running).

**Comment by evantahler** [comment] 2020-06-08 17:34
Hello @cuongtran3001! I wanted to check in and see if you were able to try the ideas above.  Thanks!

**Comment by cuongtran3001** [comment] 2020-06-09 05:04
Hi Evan,
I am using Ubuntu to run the Grouparoo. After using your suggestion, i got the issue:

<img width="662" alt="Capture" src="https://user-images.githubusercontent.com/4277357/84107912-1cc18300-aa49-11ea-9a5d-0078c140faa4.PNG"> 

Try to create/remove dir grouparoo/apps/local-public/node_modules/@grouparoo/core/web/tmp but not sucess.

Thank for your help.

**Comment by evantahler** [comment] 2020-06-09 19:43
Thanks @cuongtran3001!

It looks like you've cloned this monorepo, and are running one of the example apps (that's helpful to note in the future as well).  The 2 PRs linked above should help with that startup issue.  Please pull `master` and let me know if that works for you!   

I've spun up an Ubuntu environment to test on, and I'm able to load `.env` files just fine.  Can you please confirm that you have placed the `.env` file within the app's directory that you are trying to run?  For example, if I'm running `apps/staging-public`:

```shell
> ls -la
evan@ubuntu-vm:~/workspace/grouparoo/grouparoo/apps/staging-public$ ls -la
total 44
drwxrwxr-x 3 evan evan  4096 Jun  9 19:32 .
drwxrwxr-x 4 evan evan  4096 Jun  9 19:25 ..
-rw-rw-r-- 1 evan evan   573 Jun  9 19:32 .env # <--- Here 
-rw-rw-r-- 1 evan evan   573 Jun  9 19:25 .env.example
-rw-rw-r-- 1 evan evan 16725 Jun  9 19:25 LICENSE.txt
drwxrwxr-x 3 evan evan  4096 Jun  9 19:28 node_modules
-rw-rw-r-- 1 evan evan  1636 Jun  9 19:25 package.json
```

**Comment by cuongtran3001** [comment] 2020-06-10 02:18
Hi @evantahler,
Thank again for your support.

#I have cloned new repo to test again. Here is my structure local-public folder:
<img width="423" alt="lsla" src="https://user-images.githubusercontent.com/4277357/84219530-f3f9c600-aafa-11ea-967f-be3821c6e952.PNG">

#And this is content of .env file:
<img width="467" alt="env" src="https://user-images.githubusercontent.com/4277357/84219534-f65c2000-aafa-11ea-9c89-4b81febbd15d.PNG">

#When running command npm start, i got this issue related to server token:
<img width="665" alt="npm_start" src="https://user-images.githubusercontent.com/4277357/84219537-f8be7a00-aafa-11ea-8840-f83f133a5012.PNG">

#So I add the environment variable and the last issue + token issue was gone. But it introduce new bug:
<img width="663" alt="new_bug" src="https://user-images.githubusercontent.com/4277357/84219539-fb20d400-aafa-11ea-8869-d6c1f10dc9f0.PNG">

Could you please look at and let me now which config I am missing.

Thank,
Cuong Tran

**Comment by evantahler** [comment] 2020-06-10 22:59
Thank you for continuing to share all this information!  

The `cannot read property server of undefined` error should be fixed by https://github.com/grouparoo/grouparoo/pull/329.  However, this is indicative of a larger problem - your `.env` is still not being loaded, and it looks like none of your plugins are getting loaded either.  If you really did have `WEB_URL=WEB_URL=http://localhost:3000`, the web server and websocket server should have booted OK.   I would also have expected to see a lot more `registering plugin` lines in your output, as there are more plugins listed in `/apps/local-public/package.json`:

```
2020-06-10T22:38:18.712Z - info: registering grouparoo plugin: @grouparoo/core/manual
2020-06-10T22:38:18.712Z - info: registering grouparoo plugin: @grouparoo/core/events
2020-06-10T22:38:18.713Z - info: registering grouparoo plugin: @grouparoo/mysql
2020-06-10T22:38:18.713Z - info: registering grouparoo plugin: @grouparoo/postgres
2020-06-10T22:38:18.714Z - info: registering grouparoo plugin: @grouparoo/mailchimp
2020-06-10T22:38:18.714Z - info: registering grouparoo plugin: @grouparoo/logger
2020-06-10T22:38:18.714Z - info: registering grouparoo plugin: @grouparoo/csv
2020-06-10T22:38:18.714Z - info: registering grouparoo plugin: @grouparoo/email-authentication
2020-06-10T22:38:18.714Z - info: registering grouparoo plugin: @grouparoo/google-sheets
2020-06-10T22:38:18.715Z - info: registering grouparoo plugin: @grouparoo/sailthru
```

I see that you are using `sudo` to run the project... can you share why?  There may be file permission differences between your local user and the node/grouparoo process.  The other issue might be that you don't have the `dot-env` package installed properly... which should be getting installed for you from `@grouparoo/core`

I recommend trying the other example app, `staging-public` first.  `local-public` is not built by the default install process.  Be sure to run `lerna link` (or `../../node_modules/.bin/lerna link`) within that project before starting it .`staging-public` is part of the setup process, and it might be simpler to get started with.

From a fresh clone of this repo, I would expect the following to work:
1. `git clone ... && cd grouparoo`
2. `npm install` (which calls `lerna bootstrap`)
3. `cd apps/local-public`
4. `cp .env.example .env`
5. `npm install`
5. `lerna link`
6. (create databases)
7. `npm run dev`

**Comment by evantahler** [comment] 2020-06-10 23:02
Also, as a reminder, if you are interested in trying Grouparoo vs developing against it, it will be much easier to start here: https://github.com/grouparoo/grouparoo/blob/master/documents/deployment/getting-started.md

**Comment by cuongtran3001** [comment] 2020-06-11 01:32
Hi @evantahler,

I will follow your steps to test again and will back to you if any problem. Actually, I am trying to setup the demo to see how it work and see if we can apply it to our customers. We don't have skills or resources to develop it. 

Beside, can you please let me know with website Monthy Active User is about 3-5 million, is it ok to use Grouparoo?

Thank

**Comment by evantahler** [comment] 2020-06-11 23:14
Looks like you got it working! 
Let us know if you need more help.

**Closed as completed by evantahler** 2020-06-11 23:14 UTC
Labels: bug, question

**Comment by Tate17** [comment] 2021-09-15 06:02
> Hi Grouparoo team,
> 
> I have followed the instruction to run app and go to step 4:
> 
> **Run npm start to start the server and visit http://localhost:3000 to get started. Follow the on-screen instructions to create your account and first team.**
> 
> 
> 
> Here is the result:
> 
> 
> 
> > @grouparoo/app-local-public@0.1.2 start /mnt/d/Project/grouparoo/apps/local-public
> 
> > cd node_modules/@grouparoo/core && GROUPAROO_MONOREPO_APP=local-public ./api/bin/start
> 
> 
> 
> 2020-06-01T09:12:27.613Z - info: registering grouparoo plugin: @grouparoo/core/manual
> 
> 2020-06-01T09:12:27.615Z - info: registering grouparoo plugin: @grouparoo/core/events
> 
> 2020-06-01T09:12:27.617Z - notice: pid: 424
> 
> 2020-06-01T09:12:27.618Z - notice: environment: development
> 
> 2020-06-01T09:12:27.619Z - info: *** Starting Actionhero ***
> 
> 2020-06-01T09:12:27.622Z - info: using path "/mnt/d/Project/grouparoo/apps/local-public/node_modules/@grouparoo/core/api/files/development" for Grouparoo file storage
> 
> 2020-06-01T09:12:27.633Z - info: actionhero member 192.168.1.53 has joined the cluster
> 
> 2020-06-01T09:12:27.689Z - notice: server ID: 192.168.1.53
> 
> 2020-06-01T09:12:27.690Z - notice: *** Actionhero Started ***
> 
> 
> 
> When opening the brower to access http://localhost:3000 but nothing happend and get the message: This site can’t be reached
> 
> 
> 
> Any step that i am missing please help to correct?
> 
> 
> 
> Tks,
> 
> Cuong Tran
> 
>

**Comment by evantahler** [comment] 2021-09-15 06:22
Hi @Tate17!  

From the logs you shared, it looks like the web server hasn't been started.  Also, you may have just copied and pasted the comment at the start of this issue... did you have something new to share?

Please confirm that you:
* Are running on a Linux or OSX system (or WSL on Windows)?
* Have a `.env` file that includes [WEB_SERVER and PORT](https://www.grouparoo.com/docs/installation/node#step-2-generate-packagejson-and-env)?  

Also, it looks like you are using a rather old version of Grouparoo (`@grouparoo/core/manual` and `@grouparoo/core/events` have been removed).  Please upgrade to the latest versions!
