### ISSUE TITLE
Feature Request: Ability to add custom code to our property configs

### ISSUE THREAD

**Issue by andyjih** [grouparoo/grouparoo#1721] opened 2021-04-29 20:56 UTC
Some users have asked for the ability to add custom code to property definitions. For example being able to write a function that takes a part of a user_id and mapping that to a specific property value.

**Comment by evantahler** [comment] 2021-04-29 22:41
Possibly a duplicate of https://github.com/grouparoo/grouparoo/issues/780

**Comment by evantahler** [comment] 2021-08-31 00:49
Closed by https://github.com/grouparoo/grouparoo/pull/2146

**Closed as completed** 2021-08-31 00:49 UTC
Labels: enhancement
