### ISSUE TITLE
An unexpected error occured when clicking on a profile

### ISSUE THREAD

**Issue by smogili1** [grouparoo/grouparoo#586] opened 2020-08-06 07:11 UTC
**Describe the bug**
I get the error message: An unexpected error occured when I click on a profile to view. 

In the browser console, I see this error: 

main-32946210fba4e52212f5.js:1 TypeError: Cannot read property 'values' of undefined
    at r (edit-c897c2ec431c9e3a6449.js:1)
    at S (edit-c897c2ec431c9e3a6449.js:1)
    at Gi (framework.b165b577f2845b644e38.js:1)
    at ko (framework.b165b577f2845b644e38.js:1)
    at xu (framework.b165b577f2845b644e38.js:1)
    at wu (framework.b165b577f2845b644e38.js:1)
    at du (framework.b165b577f2845b644e38.js:1)
    at framework.b165b577f2845b644e38.js:1
    at t.unstable_runWithPriority (framework.b165b577f2845b644e38.js:1)
    at $l (framework.b165b577f2845b644e38.js:1)

**Environment (please complete the following information):**
 - OS: Deployed with docker compose using instructions in README.md
 - Browser: Chrome
 - Grouparoo Version: 0.1.8

**Comment by evantahler** [comment] 2020-08-06 15:56
Thank you for reporting this bug @smogili1.

Can you please share more information about your server when you saw this error: 
- Had you previously successfully viewed any profiles previously?
- Had you already created profile properties?
- Can you please share the URL you were attempting to view when the error occurred? (I'm guessing `/profile/pro_{uuid}/edit`

Thank you!

**Comment by smogili1** [comment] 2020-08-06 16:06
Hi @evantahler - 

Had you previously successfully viewed any profiles previously?
No I haven't, first time using this. I setup the profiles by adding a postgres data source which contains our customer data. 

Had you already created profile properties?
Yes, have three properties for each profile setup. 

Can you please share the URL you were attempting to view when the error occurred? (I'm guessing /profile/pro_{uuid}/edit
URL: 
http://localhost:3000/profile/pro_5331fbe9-8544-4c5b-901a-7681d068b4ac/edit

attaching screenshot of the profile properties setup

![image](https://user-images.githubusercontent.com/36517810/89554705-0e32e600-d7c4-11ea-9208-fc68eb8a64b2.png)

**Comment by evantahler** [comment] 2020-08-08 00:21
Hello again @smogili1 - 

I'm not able to reproduce the error you are seeing.  I've added better error logging (via https://github.com/grouparoo/grouparoo/pull/589) to our frontend, which will help us pinpoint what's going wrong.  We'll release a new version soon, and I'll ask that you try again so we can get some better information.  

Thanks for your patience!

**Comment by evantahler** [comment] 2020-08-08 22:56
Version 0.1.9 of Grouparoo has been released, and the docker images have been updated.  Can you give it a try again?

**Comment by smogili1** [comment] 2020-08-09 01:37
Hi Evan, 

Thanks! Here's what I see now:

![image](https://user-images.githubusercontent.com/36517810/89722976-54936b00-d9a5-11ea-9bbe-d3f13f284e65.png)

Btw are there docs on how I can use javascript tracking code ?

**Comment by smogili1** [comment] 2020-08-09 02:40
Looks like this could be due to our profile not having email addresses ? 

Not all of our users have emails entered, we use telegram usernames instead.

**Comment by smogili1** [comment] 2020-08-09 07:08
I can confirm that adding a new unique profile property for email resolves this error. You might consider updating this so the getprofiledisplayname can be configured in the profile properties screen instead of only looking for emails. 

I added a dummy field with the email property even though I don't have that column in my user table.

**Comment by evantahler** [comment] 2020-08-10 21:47
Great suggestion! That will be addressed in https://github.com/grouparoo/grouparoo/pull/591

**Closed as completed** 2020-08-10 23:01 UTC
Labels: bug, question
